### ISSUE TITLE
Plugin lib not found, make install error

### ISSUE THREAD

**Issue by riyoji37** [catsout/wallpaper-engine-kde-plugin#214]
im new to linux and i wanted to make wallpaper engine to work in kde but i just cannot make it work no matter what. when i try to install it and use it and after i installed the dependencies, it always says plugin lib not found. and when i try to build and install it with the code in the readme, i always get this error at the lib install (sudo make install):

Install the project...
-- Install configuration: "Release"
CMake Error at src/cmake_install.cmake:65 (file):
file INSTALL cannot find
"/home/user/wallpaper-engine-kde-plugin/build/src/libWallpaperEngineKde.so":
No such file or directory.
Call Stack (most recent call first):
cmake_install.cmake:42 (include)

make: *** [Makefile:97: install] Error 1

and i got this error too when i try to build and install too:

Scanning dependencies of target wpUtils
[ 1%] Building CXX object src/backend_scene/src/Utils/CMakeFiles/wpUtils.dir/Logging.cpp.o
In file included from /home/user/wallpaper-engine-kde-plugin/src/backend_scene/src/Utils/Logging.cpp:1:
/home/user/wallpaper-engine-kde-plugin/src/backend_scene/src/Utils/include/Utils/Logging.h:4:10: fatal error: span: No such file or directory
4 | #include
| ^~~~~~
compilation terminated.
make[2]: *** [src/backend_scene/src/Utils/CMakeFiles/wpUtils.dir/build.make:63: src/backend_scene/src/Utils/CMakeFiles/wpUtils.dir/Logging.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2043: src/backend_scene/src/Utils/CMakeFiles/wpUtils.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

i saw the plugin in the desktop setting and i could choose between wallpapers but the wallpapers won't show in desktop, but now i can't even see the wallpapers in the plugin options because it gives a new error for that too:

Python helper run failed:
Trackback (most recent call last):
File "/home/user/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/pyext.py, line 125, in
def get_folder_list(path: str, _opt: dict = {}) -> dict | None:
TypeErrror: unsupported operand type(s) for |: 'Type' and 'NoneType'

anyone has an idea why it went so bad for me? im so lost

im using Linux Mint 20.3 x86_64

**Comment by catsout** [comment]
Update to 22.04 will solve all your problem.

**Comment by catsout** [comment]
I fixed the python error, please try the new commit.

**Comment by riyoji37** [comment]
im not using ubuntu, im using linux mint and the 21 is the newest version, not 22.04. or did you meant to update something else?

also the pyton error is gone, but my wallpapers don't show up now in the desktop menu. or i just make the steam folder unhidden?

**Comment by catsout** [comment]
Seems linux mint 21 has gcc 10, please install it, and remove gcc 9.  
Then try to make again.

**Comment by riyoji37** [comment]
i tried to install gcc 10 and remove 9 with sudo apt install gcc-10 and sudo apt remove gcc-9 but now it can't find any compiler. do i have to install 10 differently or remove 9 differently?
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:8 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:8 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!

**Comment by riyoji37** [comment]
i installed linux mint 21 and now i can install it without errors, but i still have a python helper run failed message with lots of errors when i open it in desktop configuration, and it says the python3 websockets are missing in lib check even tho it's installed.

**Comment by catsout** [comment]
https://github.com/catsout/wallpaper-engine-kde-plugin/issues/162

**Comment by riyoji37** [comment]
Thank you! it's working now
