### ISSUE TITLE
Please make sure qtwebsockets(qml module) installed, and open this again

### ISSUE THREAD

**Issue by ImT00PhaT** [catsout/wallpaper-engine-kde-plugin#462]
Hi, I'm getting this error message when trying to set-up Wallpaper Engine. This has been an issue since I upgraded from Ubuntu 24.04 to 24.10:

![Image](https://github.com/user-attachments/assets/ddf06143-5a3a-4d75-ae1e-ce96762c459d)

This is what I get in terminal:

sudo apt-get -y install qml-module-qt-websockets
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
qml-module-qt-websockets is already the newest version (5.15.15-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by thejasgr** [comment]
Hi,

I changed the initial install command to this in Fedora 41
`sudo dnf install vulkan-headers plasma-workspace-devel kf5-plasma-devel gstreamer1-libav lz4-devel mpv-libs-devel python3-websockets qt6-qtbase-private-devel qt5-qtx11extras-devel qt6-qtwebchannel-devel qt6-qtwebsockets-devel cmake
`

and it worked for me. So give it a shot.

**Comment by ImT00PhaT** [comment]
> Hi,
> 
> I changed the initial install command to this in Fedora 41 `sudo dnf install vulkan-headers plasma-workspace-devel kf5-plasma-devel gstreamer1-libav lz4-devel mpv-libs-devel python3-websockets qt6-qtbase-private-devel qt5-qtx11extras-devel qt6-qtwebchannel-devel qt6-qtwebsockets-devel cmake `
> 
> and it worked for me. So give it a shot.

I changed to sudo apt since I'm on ubuntu and all the packages come up with error: unable to locate package. I'm getting this only works for fedora since all the resolutions I could find here are for Fedora.

**Comment by Ghoul072** [comment]
Same issue on OpenSUSE Tumbleweed with KDE Plasma 6.3.0 and Qt version 6.8.2

**Comment by Ghoul072** [comment]
> > Hi,
> > I changed the initial install command to this in Fedora 41 `sudo dnf install vulkan-headers plasma-workspace-devel kf5-plasma-devel gstreamer1-libav lz4-devel mpv-libs-devel python3-websockets qt6-qtbase-private-devel qt5-qtx11extras-devel qt6-qtwebchannel-devel qt6-qtwebsockets-devel cmake `
> > and it worked for me. So give it a shot.
> 
> I changed to sudo apt since I'm on ubuntu and all the packages come up with error: unable to locate package. I'm getting this only works for fedora since all the resolutions I could find here are for Fedora.

I got mine fixed by instaling qt6-websockets-imports in OpenSUSE. The Debian equivalent, if I'm not mistaken, should be just `qt6-websockets`

**Comment by Yastruhank** [comment]
try to install the following packages？
```
sudo apt install qml6-module-qtwebsockets qml6-module-qtwebchannel
```

**Comment by ImT00PhaT** [comment]
> try to install the following packages？
> 
> ```
> sudo apt install qml6-module-qtwebsockets qml6-module-qtwebchannel
> ```

This sort of works.
Now I can see my wallpapers, but when I apply, it's blank.

I checked "About" and it says "warning: the lib version is inconsistent with the plugin version"
the plugin version is 0.5.5

Any idea what this means?
I tried deleting the folder and reinstalling using the readme instructions, but it did not resolve the issue.

There were errors relating to cmake, but I forgot to take screenshots.

**Comment by ImT00PhaT** [comment]
Okay, I fixed the issue, so this can be marked as resolved.

I downloaded and installed apt plasma 5 from this link: https://github.com/slynobody/SteamOS-wallpaper-engine-kde-plugin
Then I uninstalled as stated in the instructions, deleting the "wallpaper-engine-kde-plugin" folder and "com.github.catsout.wallpaperenginekde" folder from /.local/share/plasma/wallpapers.

I reinstalled as stated in the instructions, but I changed a few commands "git clone -b qt5" and did sudo for "cmake --install build". I restarted after build and install, then I went back to the github steamos link installed plasma 6-6.2 to fix the "plugin lib not found" and "inconsistent" issue.

This was an arduous and tedious process. It also breaks my plasmashell, which I think happens when I keep changing wallpapers, so I have to pick one that I want to use and apply, and probably do the same if I want to change my wallpaper next time.

If anyone attempts this, use timeshift. IT'S A LIFE SAVER!
